fix throttling
outscale-dev/terraform-provider-outscale pull request #215
Opened 2022-10-31 07:29 UTC by outscale-toa

fixes #207

2022-10-31 09:54 UTC, FredericBerot-Armand requested changes

2022-10-31 09:54 UTC, FredericBerot-Armand commented on utils/utils.go
> +	if errCode == Throttled || errCode == ResourceConflict {
Just add a warning log for 409 errors, to detect consistency issues

2022-11-09 13:59 UTC, outscale-mzi commented
Hello @outscale-toa  :) 
Tests OK on  PR  fix throttling #215  binary.

2022-11-18 14:39 UTC, FredericBerot-Armand approved these changes
Seems Fine ^^

2022-11-18 14:41 UTC, merged