Fix segfault throttling
outscale-dev/terraform-provider-outscale pull request #256
Opened 2022-12-01 10:36 UTC by FredericBerot-Armand

closes #245

2022-12-01 13:47 UTC, outscale-toa requested changes

2022-12-01 14:02 UTC, FredericBerot-Armand commented on outscale/config.go
> +	}*/
Yes, i forget this one, it's done

2022-12-01 14:10 UTC, outscale-mzi commented
Hello @FredericBerot-Armand, 
Tests **OK** on PR #256  binary:
- wrong Proxy:
```
│ Error: Error creating OAPIKeyPair: Post "https://api.in-west-1.outscale.com/api/v1/CreateKeypair": context deadline exceeded
```

- wrong endpoint:

```
Error: Error creating OAPIKeyPair: 400 Bad Request
│ 
│   with outscale_keypair.keypair01,
│   on windows_vm.tf line 1, in resource "outscale_keypair" "keypair01":
│    1: resource "outscale_keypair" "keypair01" {
│ 
```

2022-12-05 08:45 UTC, outscale-toa approved these changes

2022-12-05 08:45 UTC, merged